version: "3"
services:
 server:
  build: ./
  container_name: server
  volumes:
   - /var/www/kemuro/:/public/
   - client_node_modules:/node_modules
  ports:
   - "127.0.0.1:3001:3001"
  restart: unless-stopped